wandb_version: 1

model.hidden_dim:
  desc: null
  value: 256
training.optimizer_hyperparameter.lr:
  desc: null
  value: 0.004644309423569652
training.scheduler.scheduler_type:
  desc: null
  value: exponential
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739026644.447698
    t:
      1:
      - 1
      - 5
      - 30
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 13
      - 14
      - 23
      4: 3.10.14
      5: 0.15.4
      8:
      - 6
