wandb_version: 1

model.hidden_dim:
  value: 128
training.optimizer_hyperparameter.lr:
  value: 0.0006778364422552321
training.optimizer_hyperparameter.weight_decay:
  value: 0.0009933578975506285
training.scheduler.scheduler_type:
  value: constant
