wandb_version: 1

model.hidden_dim:
  value: 256
training.optimizer_hyperparameter.lr:
  value: 0.0022963745675349373
training.optimizer_hyperparameter.weight_decay:
  value: 0.0008700206319683043
training.scheduler.scheduler_type:
  value: exponential
