wandb_version: 1

model.hidden_dim:
  value: 256
training.optimizer_hyperparameter.lr:
  value: 0.0010129434138427978
training.optimizer_hyperparameter.weight_decay:
  value: 0.0002634780122048754
training.scheduler.scheduler_type:
  value: constant
