wandb_version: 1

model.hidden_dim:
  value: 512
training.optimizer_hyperparameter.lr:
  value: 0.008933745056998392
training.optimizer_hyperparameter.weight_decay:
  value: 0.0007358216565761986
training.scheduler.scheduler_type:
  value: constant
