wandb_version: 1

model.hidden_dim:
  value: 256
training.optimizer_hyperparameter.lr:
  value: 0.004606622376529076
training.optimizer_hyperparameter.weight_decay:
  value: 3.236936354050835e-05
training.scheduler.scheduler_type:
  value: constant
