wandb_version: 1

model.hidden_dim:
  value: 128
training.optimizer_hyperparameter.lr:
  value: 0.005488943158580975
training.optimizer_hyperparameter.weight_decay:
  value: 0.00015253934380846337
training.scheduler.scheduler_type:
  value: exponential
