wandb_version: 1

model.hidden_dim:
  value: 128
training.optimizer_hyperparameter.lr:
  value: 0.008259897727231694
training.optimizer_hyperparameter.weight_decay:
  value: 0.0009405187066336888
training.scheduler.scheduler_type:
  value: constant
