wandb_version: 1

model.hidden_dim:
  desc: null
  value: 128
training.optimizer_hyperparameter.lr:
  desc: null
  value: 0.00950376856388488
training.scheduler.scheduler_type:
  desc: null
  value: constant
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739026049.147038
    t:
      1:
      - 1
      - 5
      - 30
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 30
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 2
      - 13
      - 14
      - 23
      - 37
      4: 3.10.14
      5: 0.15.4
      8:
      - 6
logging:
  desc: null
  value:
    mode: online
    project: cellvit++
    notes: cellvit++
    log_comment: cellvit++ sam-h sweep
    wandb_dir: /work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/logs_finetuning
    log_dir: /work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/logs_finetuning/sweep_41q9jfnt/2025-02-08T154722_cellvit++
      sam-h sweep_e97uko8t
    level: Debug
    run_id: e97uko8t
    wandb_file: e97uko8t
    sweep_id: 41q9jfnt
sweep:
  desc: null
  value:
    method: bayes
    name: experimental_sweep
    metric:
      goal: maximize
      name: AUROC/Validation
    run_cap: 20
random_seed:
  desc: null
  value: 42
gpu:
  desc: null
  value: 0
data:
  desc: null
  value:
    dataset: DetectionDataset
    dataset_path: /work/grana_urologia/MONKEY_challenge/data/monkey_cellvit_3_cls_parallel
    train_filelist: /work/grana_urologia/MONKEY_challenge/data/monkey_cellvit_3_cls_parallel/splits/fold_0/train.csv
    val_filelist: /work/grana_urologia/MONKEY_challenge/data/monkey_cellvit_3_cls_parallel/splits/fold_0/val.csv
    normalize_stains_train: false
    normalize_stains_val: false
    num_classes: 3
label_map:
  desc: null
  value:
    '0': monocytes
    '1': lymphocytes
    '2': other
cellvit_path:
  desc: null
  value: /work/grana_urologia/MONKEY_challenge/source/sota_architectures/CellViT-plus-plus/checkpoints/SAM/CellViT-SAM-H-x40-AMP.pth
training:
  desc: null
  value:
    cache_cell_dataset: true
    batch_size: 64
    epochs: 50
    drop_rate:
      values:
      - 0.1
      - 0.3
      - 0.5
    optimizer: AdamW
    optimizer_hyperparameter:
      betas:
      - 0.85
      - 0.9
      weight_decay: 1.3974982424527856e-05
      lr: 0.00950376856388488
    early_stopping_patience: 20
    mixed_precision: true
    eval_every: 1
    scheduler:
      scheduler_type: constant
run_sweep:
  desc: null
  value: true
agent:
  desc: null
  value: null
just_load_model:
  desc: null
  value: false
model:
  desc: null
  value:
    hidden_dim: 128
